### ISSUE TITLE
S2 - 💛  README

### ISSUE THREAD

**Issue by kabianca** [kabianca/social-network#10]
### Tasks

- [x] Apresentar a ideia do projeto (rede de receitas);
- [x] Apresentar o protótipo e o primeiro feedback de pessoas consultadas;
- [x] História de Usuário 1;
- [ ] Desafios e resoluções da construção da história 1;

**Comment by kabianca** [comment]
### **Feedbacks recebidos após pesquisa UX** 
Usuário 1:
- Página de login não conversa com a timeline;
- Título da página no login não possui destaque;
- Acentuação das palavras;
- Centralizar o título de Cadastro;

Usuário 2:
- Acento nas palavras da caixa de input;
- Especificar melhor doses dos ingredientes (colher de chá, de sopa...);

Usuário 3:
- Checar o contraste entre textos e background (plugin Figma Contrast);
- Padronizar largura e altura dos botões;
- Ícones de sair e home em uma cor de maior destaque com o background;
- Evitar o caps lock pra falicitar a leitura dos usuários;
