### ISSUE TITLE
S4 - 💛 - Emitir mensagens de erros ao usuário

### ISSUE THREAD

**Issue by kabianca** [kabianca/social-network#31]
### Tasks (Cadstro e Login)

- [x] Criar campo para impressão de mensagens de erro pro usuário no Cadastro;
- [x] Criar campo para impressão de mensagens de erro pro usuário no Login;
- [x] Editar as mensagens de erro que serão impressas ao usuário de acordo com o erro alcançado;

**Comment by kabianca** [comment]
As validações seguem junto com essa tarefa, por isso puxei do backlog e as coloquei como issue.
