### ISSUE TITLE
S4 - 💛 - Validações de Campos - Cadastro

### ISSUE THREAD

**Issue by kabianca** [kabianca/social-network#32]
### Tasks

- [x] Somente usuários com contas válidas têm acesso permitido;
- [x] Quando o formulário de registro ou login é enviado, ele deve ser validado;
- [x] Não haver usuários repetidos;
- [x] A conta do usuário deve ser um email válido;
- [x] O que o usuário digita no campo de senha (input) deve ser secreto;
- [x] Os campos de nome, e-mail, senha e confirmação de senha devem ser preenchidos pelo usuário;
- [x] O campo de e-mail deve ser um e-mail válido (text@text.tex);
- [x] O campo de nome deve ser uma string;
- [x] O campo de senha deve possuir o mínimo de 6 dígitos;
