### ISSUE TITLE
🔴 HTML SPA - Login

### ISSUE THREAD

**Issue by kabianca** [kabianca/social-network#8]
### Tasks HTML

- [ ] Documentação sobre SPA - [video Palomita](https://www.youtube.com/watch?v=hf8x3A1e57Y)
- [ ] Inserção da logo;
- [ ] Inserção dos cabeçalhos da página;
- [ ] Inserção dos campos de input (usuário e senha);
- [ ] Botão LOGAR;
- [ ] Conferir se os dados inseridos no input são coletados com o clique do botão;
- [ ] Inserção do botão para logar usando conta do google (firebase);

### Tasks JavaScript

- [ ] Construir a template string para cada "página";
- [ ] Construir a lógica do comportamento de cada página (o que deve acontecer ao clicar em botões e/ou links);
- [ ] Constuir a lógica das rotas;
