### ISSUE TITLE
S3 - 💛  Primeira etapa de construção do CSS

### ISSUE THREAD

**Issue by kabianca** [kabianca/social-network#9]
Inicio da estilização das páginas seguindo o protótipo e com base nos elementos necessário da definição de pronto da história 1.

### Tasks

- [x] Estilizar página de login;
- [x] Estlizar página de cadastro;
- [x] Estilizar página da timeline;
- [x] Separa elementos em  "Já possui conta? (...) Entrar" e "Não possui conta? (...) Cadastre-se";
- [x] Atribuir id ou class a cada elemento que se repete nos css's; (aqui usei o padrão de seletor de elemento a partir de um parente elemento)
- [x] ajuste da imagem de fundo/rodapé/cabecalho; (optamos por trocar a imagem de fundo para uma única sem a pimenta, o que resolveu o problema);

Depois do commit marina-13-set do dia 15/09:
- [ ] ajustar botão de login google (border-radius);
- [ ] espaçamento entre elementos página login (pq tirou a primenta);
- [ ] ajustar variavel dar fontes;
- [ ] fixar rodapé no fim da janela como menu flutuante;
- [ ] ajustar distancia entre "já possui conta? Entrar";

**Comment by kabianca** [comment]
### Ordem de elementos CSS: 

1.  background, 
2. position, 
3. display, 
4. ramificações display, 
5. bottom (left, right, top), 
6. margin, 
7. border, 
8. padding, 
9. tamanho (width e heigth), 
10. decorações (botao e link), 
11. color, 
12. font-size, 
13. font-weigth, 
14. text-align, 
15. demais texts

**Comment by kabianca** [comment]
Essa tarefa estava inicialmente planejada para a Sprint 3, mas acabamos iniciando na Sprint 2 dado que sobrou um tempinho após a conclusão das tarefas planejadas para a segunda sprint.
